import numpy as np
import matplotlib.pyplot as plt


def plot_mp(t, x, y, u):
    plt.figure(1)
    # plt.title("Mecânica Pulmonar - Pressões")
    plt.xlabel("Tempo [s]")
    plt.ylabel("Pressão [cmH2O]")
    plt.plot(t, np.array(x["Pl"]), color="r", label="Pl")
    plt.plot(t, np.array(x["Ptr"]), color="b", label="Ptr")
    plt.plot(t, np.array(x["Pb"]), color="g", label="Pb")
    plt.plot(t, np.array(x["PA"]), color="k", label="PA")
    plt.plot(t, np.array(x["Ppl"]), color="y", label="Ppl")
    plt.legend(loc="upper right")
    # plt.show()

    plt.figure(2)
    # plt.title("Mecânica Pulmonar - Fluxos")
    plt.xlabel("Tempo [s]")
    plt.ylabel("Fluxo [L/s]")
    plt.plot(t, np.array(y["V_dot"]), color="r", label="V_dot")
    plt.plot(t, np.array(y["VA_dot"]), color="b", label="VA_dot")
    plt.legend(loc="upper right")
    # plt.show()

    plt.figure(3)
    # plt.title("Mecânica Pulmonar - Volumes")
    plt.xlabel("Tempo [s]")
    plt.ylabel("Volume [L]")
    plt.plot(t[1:], np.array(y["VA"])[1:], color="k", label="VA")
    plt.plot(t[1:], np.array(y["V"])[1:], label="V")
    plt.legend(loc="upper right")

    plt.figure(4)
    # plt.title("Mecânica Pulmonar - Volumes")
    plt.xlabel("Tempo [s]")
    plt.ylabel("Volume [L]")
    plt.plot(t[1:], np.array(y["Vl"])[1:], color="r", label="Vl")
    plt.plot(t[1:], np.array(y["Vtr"])[1:], color="b", label="Vtr")
    plt.plot(t[1:], np.array(y["Vb"])[1:], color="g", label="Vb")
    plt.plot(t[1:], np.array(y["VD"])[1:], color="y", label="VD")
    plt.legend(loc="upper left")

    plt.figure(5)
    # plt.title("Mecânica Pulmonar - Pressões de entrada")
    plt.xlabel("Tempo [s]")
    plt.ylabel("Pressão [cmH2O]")
    plt.plot(t, np.array(u["Pmus"]), color="r", label="Pmus")
    plt.plot(t, np.array(u["dPmus"]), color="k", label="dPmus")
    # plt.plot(t, derivada_pmus, color="b", label="derivada_pmus")
    plt.legend(loc="upper left")
    plt.show()
